CREATE TABLE IF NOT EXISTS bars (
  tf INTEGER NOT NULL DEFAULT 1,
  t INTEGER PRIMARY KEY,
  o REAL NOT NULL,
  h REAL NOT NULL,
  l REAL NOT NULL,
  c REAL NOT NULL,
  v REAL NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_bars_t ON bars(t);
CREATE INDEX IF NOT EXISTS idx_bars_tf_t ON bars(tf, t);
