name = "goldsignalsx-worker"
main = "worker.js"
compatibility_date = "2025-01-15"

[vars]
UPSTREAM_URL = "https://gold-ticks.example.workers.dev/price"
ALLOW_ORIGINS = '["*"]'
RL_LIMIT = "180"

[[kv_namespaces]]
binding = "GSX_KV"
id = "8a1e80ff17ec4a73bb32a15ad1e92552"

[[d1_databases]]
binding = "GSX_DB"
database_name = "gsx_db"
database_id = "2bd08f22-1829-48b9-b889-3b2693f2d8ea"

[triggers]
crons = ["*/5 * * * *"]
